name: project-plant-vasculature
channels:
  - conda-forge
dependencies:
  - ca-certificates
  - matplotlib
  - openssl
  - pip
  - polars=0.20
  - python=3.10
  - rasterio=1.3
  - scikit-image=0.23
  - shapely=2.0
  - tensorflow[and-cuda]
  - tqdm
  - zarr=2.18
  - pip:
    - gputools
    - stardist==0.9.1
