name: project-plant-vasculature
channels:
  - conda-forge
  # - ilastik-forge
dependencies:
  - ca-certificates
  - imagecodecs=2023.9.18
  - pandas=2.2
  # - ilastik-core=1.4.1b15
  - matplotlib
  - openssl
  - pip
  - python=3.10
  - scikit-image=0.23
  - tqdm
  - zarr=2.18
