name: project-plant-vasculature
channels:
  - conda-forge
dependencies:
  - ca-certificates
  - joblib
  - matplotlib
  - openssl
  - pip
  - polars=0.20
  - python=3.10
  - rasterio=1.3
  - scikit-image=0.23
  - shapely=2.0
  - tensorflow
  - tqdm
  - zarr=2.18
  - seaborn=0.13.2
  - pyarrow=16.1.0
  - pip:
      - gputools
      - stardist==0.9.1
