name: project-plant-vasculature
channels:
  - conda-forge
  - ilastik-forge
dependencies:
  - ca-certificates
  - ilastik=1.4
  - matplotlib
  - openssl
  - pip
  - python=3.10
  - tqdm
  - scikit-image=0.23
  - zarr=2.18
